.travis.yml
appveyor.yml

Adding Erik and Andrei since they have been reviewing this crate before and adding Simon since I know he is interested in the RPC stuff in general.
This crate does not have many tests yet. But the CI serves the purpose to make sure it will at least compile on all platforms. Something that might be easy to miss when the developer is only using one of them. The plan is to add integration/system tests later that actually sets up a server and does some real communication to test everything all the way through.
CI configs mostly copied from our newclient repo, but a bit simpler. No hard requirements on format or anything. (Sidenote: I format this repo with the latest `rustfmt-nightly` which I think is much nicer than `rustfmt 0.8.3`, I think we should switch newclient over at some point.)
If …

Add Travis and Appveyor configs

---

http/Cargo.toml

In order to publish a crate it must depend only on other published crates. So I had to make this difference to be able to upload the http crate to crates.io
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/jsonrpc-client-rs/11)

Make http depend on released core

---

core/Cargo.toml
core/src/lib.rs

Having circular dependencies like this really created kind of troubles when releasing and uploading to crates.io. Since crates.io only accept dependencies to released crates I needed to point core to 0.2 of the http crate and vice versa. So none of them could be uploaded first since the other was missing. I circumvented that and uploaded anyway, but now I want to remove this circular stuff completely.
We can still have the example code using the http crate, I just tag it with `ignore` so rustdoc does not try to compile or run it. So that puts a bit more responsibility on us it the future to make sure the docs are correct, but at least we don't have a circular dependency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Removing dev-dependency on http in core

---

core/src/macros.rs

I have now released version `0.2.0` of these two crates. But upon reading the docs I realized that it's not very nice that the docs show the `expand_params` macro. It is never supposed to be used by anyone using this crate. But it must be exported, otherwise we can't call it from our public macro `jsonrpc_client`.
Then one can hide public stuff from the docs in this way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/jsonrpc-client-rs/18)

Hide expand_params macro from documentation

---

core/Cargo.toml
http/Cargo.toml

Lots of small changes. Most notably the motherload of errors it spewed up on nightly are gone.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/jsonrpc-client-rs/21)

Update error-chain to 0.11

---

core/Cargo.toml
http/Cargo.toml

Add the badges metadata. It makes CI badges show up on crates.io directly. Not super important, but easy to add and is nice for an active project.
Also found that the repository url was wrong.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/jsonrpc-client-rs/22)

Add badges and fix repository url

---

CHANGELOG.md
core/Cargo.toml
core/src/lib.rs
core/src/response.rs
http/Cargo.toml

I realized it was madness to manually implement going from a `serde_json::Value` to a `jsonrpc_core::Error`. That can of course be done automatically since both are fully serializable.
Also upgraded to newer `jsonrpc-core` when at it.
The dep change in `http` is because when doing local development it's bothersome to point to the release version. Then changes you do locally won't get used. Better to always point to the local versions in the code and then just manually change in the working directory to some fixed release when doing `cargo publish`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/jsonrpc-client-rs/23)

Use existing error deserialization

---

http/Cargo.toml
http/README.md
http/src/lib.rs
http/tests/localhost.rs

This is something I wanted from the start, but put of because of time constraints and laziness.
The first test in this crate that actually does a real RPC call over the network. More than a test it works as a nice example for how to actually use these crates in a real scenario.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/jsonrpc-client-rs/24)

Add integration test

---

CHANGELOG.md

It's hard to remember the change log! Good to update now especially since there has been a release since it was last updated.
I know it's at least as hard to remember the change log as a reviewer as it is for the one writing the feature/PR. So I'm of course not blaming anyone. But would be nice if we could get it into the process to remember to update the change log in every feature branch, and in reviews point it out and not accept changes that are not described in the log.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/jsonrpc-client-rs/25)

Update change log to show 0.2.1 release

---

http/src/lib.rs
http/tests/localhost.rs

I found a bug in the http transport implementation. I think this is part of the error @pronebird had last week. It won't make it easier to connect to master, but it will not make the http event loop crash on a dropped `RpcRequest`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/jsonrpc-client-rs/26)

Don't crash on dropped RpcRequest in http transport

---

core/src/response.rs
http/Cargo.toml
http/tests/localhost.rs

Had to remove `env_logger` from the tests. Since the new `env_logger 0.5` now panic in `init()` instead of returning an error I can't run it in multiple tests since the last one to run will panic. No big deal.
Also, removing `check_response` and adding the little code it contained to where it was used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/jsonrpc-client-rs/29)

Simplify response check

---

CHANGELOG.md
http/Cargo.toml
http/src/lib.rs
http/tests/custom_headers.rs

HttpHandle can be configured to include custom HTTP headers in the RPC
requests it sends.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/jsonrpc-client-rs/32)

Add support for custom HTTP headers

---

CHANGELOG.md
http/src/lib.rs

Adding some forgotten things to the changelog to make it up to date with the current state.
Also moved a `#[cfg]` attribute to after the documentation. We didn't have any other instance of this to stay consistent with. But in other crates we usually put it after the documentation, and that has been my impression is the most common way as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/jsonrpc-client-rs/35)

Add items to changelog

---

.travis.yml
core/src/lib.rs
core/src/response.rs
http/src/client_creator.rs
http/src/lib.rs
http/tests/common/mod.rs
http/tests/custom_headers.rs
http/tests/localhost.rs
rustfmt.toml

The main change here is to add Travis CI runs for Rust 1.24.0. For a library it's good to keep track of the oldest supported compiler it build under. That way we can bump the major release whenever we break that compatibility.
I also updated the rustfmt settings and ran the formatter, since there has been multiple new releases since this was last formatted. The removal of `rustfmt.toml` settings is because they are now `true` by default. I copied the settings from `mullvadvpn-app`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/jsonrpc-client-rs/36)

Test oldest supported

---

CHANGELOG.md
core/Cargo.toml
core/src/lib.rs
http/Cargo.toml
http/src/lib.rs

error-chain finally fixed the warnings it produced on nightly. So upgrading. Also publicly exporting it. Otherwise it's inconvenient to reach the `display_chain()` method on the errors, if we don't re-export that trait.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/jsonrpc-client-rs/37)

Upgrade error-chain to 0.12 and publicly export it

---

Cargo.toml
ipc/Cargo.toml
ipc/src/lib.rs

This PR adds an IPC crate. I'm unsure whether to leave this as is or remove the `IpcTransport` struct and have the same functionality with plain functions returning the Sink/Stream pair.
This crate currently depends on a self-hosted dependency - `parity-tokio-ipc = { git = "https://github.com/mullvad/parity-tokio-ipc", rev = "add-client-support" }`. The pull request for that one is here - https://github.com/NikVolf/parity-tokio-ipc/pull/5. The code in both that crate and the one's it uses `tokio-named-pipes` could do with some more work, but that's a story for a day when `2018.2` is released.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/jsonrpc-client-rs/40)

Add IPC client

---

core/src/lib.rs
http/src/lib.rs
http/tests/localhost.rs
http/tests/timeout.rs
ipc/src/lib.rs

During integration, the 3 type parameters for `core::Client<W,R,E>` get a bit hard to use, and the construction is a bit ad-hoc. Thus, a `Transport` trait has been reintroduced. This means that there's some boxing now that wasn't present in the HTTP crate before, but the rest of the code is much cleaner, and the libraries will be far easier to use.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/jsonrpc-client-rs/41)

Add a Transport trait.

---

core/src/lib.rs

I found some small possible cleanups in this method.
And also, changing from `then` to `and_then` should remove a case of where the first error was just ignored.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/jsonrpc-client-rs/42)

Small fixes in send_notification

---

appveyor.yml

Running 8 builds where each can take up to 20 minutes is a bit excessive
as it the build queue for other projects on appveyor. I've removed some of the GNU toolchain build targets, as I presume they would be the least popular ones on Windows.
https://ci.appveyor.com/project/Mullvad/jsonrpc-client-rs/build/1.0.244
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/jsonrpc-client-rs/44)

Reduce build matrix

---

ipc/Cargo.toml

This PR updates the dependency `parity-tokio-ipc` to point towards the upstream repository. This is done so that it is kept up to date with what the server uses. Also, it seems that depending on an older version of the library introduces breakage on windows, which I had not foreseen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/jsonrpc-client-rs/43)

Depend on upstream IPC library

---

ipc/Cargo.toml
ipc/src/lib.rs

A recent change in `parity-tokio-ipc` broke our `jsonrpc-client-ipc` crate. This PR fixes the changes. These changes will unfortunately require more changes downstream.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/jsonrpc-client-rs/46)

Update parity-tokio-ipc dependency

---

core/Cargo.toml
core/src/id_generator.rs
core/src/lib.rs
core/src/macros.rs
core/src/select_weak.rs
core/src/server.rs

This PR adds client support for responding to RPCs and acting upon notifications received from the server.
It might still be slightly rough around the edges, but this exposes a nice set of primitives that can be used to implement subscription support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/jsonrpc-client-rs/45)

Add client support for responding to RPCs and notificaitons.

---

core/src/lib.rs
ipc/src/lib.rs

These changes make it so that unless a transport explicitly implements `DuplexTransport`, the user won't be able to use any of the `JSON-RPC` functionality that requires the server to be able to arbitrarily send requests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/jsonrpc-client-rs/49)

Segregate transports by duplex support

---

ipc/Cargo.toml

Changing so we use the same git url as the other dependencies depending on `parity-tokio-ipc`. Otherwise, currently `mullvad-daemon` has to compile and link this library twice, since it thinks it's different crates. See the `Cargo.lock` in our main repo :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/jsonrpc-client-rs/50)

Use nikvolf in url instead of NikVolf

---

pubsub/Cargo.toml
pubsub/src/lib.rs

~A lot~ _something_ has changed in the tokio ecosystem since I was last working on this crate. As such, we can have the subscription types be slightly more generic, allowing us to use the single threaded runtime in `mullvad-ipc-client` to run subscriptions.
There are also some formatting changes in here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/jsonrpc-client-rs/54)

Use a more generic Executor trait
